services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    environment:
      CLUSTER_NAME: hadoop
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - "9870:9870"
      - "9001:9000"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    networks:
      - hive-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: always
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: namenode:9870
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    networks:
      - hive-net

  metastore:
    image: docker.m.daocloud.io/apache/hive:4.1.0
    container_name: metastore
    restart: always
    depends_on:
      - namenode
      - datanode
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: derby
      SERVICE_OPTS: >
        -Dhive.metastore.warehouse.dir=/warehouse
        -Dfs.defaultFS=hdfs://namenode:9000
    ports:
      - "9083:9083"
    volumes:
      - ./data/warehouse:/warehouse
    networks:
      - hive-net

  hiveserver2:
    image: docker.m.daocloud.io/apache/hive:4.1.0
    container_name: hiveserver2
    restart: always
    depends_on:
      - metastore
    environment:
      SERVICE_NAME: hiveserver2
      IS_RESUME: "true"
      SERVICE_OPTS: >
        -Dhive.metastore.uris=thrift://metastore:9083
        -Dhive.server2.thrift.port=10000
        -Dhive.metastore.warehouse.dir=/warehouse
        -Dfs.defaultFS=hdfs://namenode:9000
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./data/warehouse:/warehouse
    networks:
      - hive-net

networks:
  hive-net:
    driver: bridge
